services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/root/app
  
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - scp_database:/var/lib/mysql
    
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=SCP!PROJECT
      - MYSQL_DATABASE=scp
      - MYSQL_RANDOM_ROOT_PASSWORD=1

volumes:
  scp_database: