services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/root/app
  
  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - scp_database:/var/lib/mysql
      - ./db-ini:/docker-entrypoint-initdb.d/
    
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=SCP!PROJECT
      - MYSQL_DATABASE=scp
      - MYSQL_RANDOM_ROOT_PASSWORD=1

  zabbix-agent:
    image: zabbix/zabbix-agent2:latest
    container_name: zabbix-agent-base-dades
    environment:
      - ZBX_PASSIVE_ALLOW=false
      - ZBX_ACTIVE_ALLOW=true
      - ZBX_SERVER_HOST=zbx.scp.com
      - ZBX_SERVER_PORT=10051
      #- ZBX_ACTIVESERVERS=zbx.scp.com:10051
      - ZBX_HOSTNAME=zbx_database
      - ZBX_REFRESHACTIVECHECKS=10
    depends_on:
      - app
      - db

volumes:
  scp_database: