services:
  bind:
#    build: .
    image: ubuntu/bind9
    ports:
      - "30053:53"
      - "30053:53/udp"
#      - "10000:10000"
    volumes:
      - ./bind:/etc/bind
      - ./bind_var:/var/cache/bind